using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using Frends.AzureBlobStorage.DownloadBlob.Definitions;
using Frends.AzureBlobStorage.DownloadBlob.Helpers;

namespace Frends.AzureBlobStorage.DownloadBlob;

/// <summary>
/// Azure Blob Storage task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Downloads a Blob from Azure Blob Storage to the local file system.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.DownloadBlob)
    /// </summary>
    /// <param name="input">Specifies which blob to download and where to save it.</param>
    /// <param name="connection">Azure Blob Storage connection parameters.</param>
    /// <param name="options">Encoding and error-handling settings.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, string FilePath, Error Error }</returns>
    public static async Task<Result> DownloadBlob([PropertyTab] Input input, [PropertyTab] Connection connection,
        [PropertyTab] Options options,
        CancellationToken cancellationToken)
    {
        try
        {
            ValidationHandler.Run(input, connection);
            var blob = ConnectionHandler.GetBlobClient(connection, input.ContainerName, input.BlobName,
                cancellationToken);
            var blobFileName = string.IsNullOrWhiteSpace(input.TargetFileName)
                ? input.BlobName
                : input.TargetFileName;
            var fullDestinationPath = Path.Combine(input.TargetDirectory, blobFileName);
            var fileName = blobFileName.Split('.')[0];
            var fileExtension = "";

            if (blobFileName.Split('.').Length > 1)
            {
                fileName = string.Join(".", blobFileName.Split('.').Take(blobFileName.Split('.').Length - 1).ToArray());
                fileExtension = "." + blobFileName.Split('.').Last();
            }

            if (input.ActionOnExistingFile == FileExistsAction.Throw && File.Exists(fullDestinationPath))
                throw new IOException(
                    "File already exists in destination path. Please delete the existing file or change the \"ActionOnExistingFile\" to Overwrite.");

            if (input.ActionOnExistingFile == FileExistsAction.Rename && File.Exists(fullDestinationPath))
            {
                var increment = 1;
                var incrementedFileName = $"{fileName}({increment}){fileExtension}";

                while (File.Exists(Path.Combine(input.TargetDirectory, incrementedFileName)))
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    increment++;
                    incrementedFileName = $"{fileName}({increment}){fileExtension}";
                }

                fullDestinationPath = Path.Combine(input.TargetDirectory, incrementedFileName);
                blobFileName = incrementedFileName;
                await blob.DownloadToAsync(fullDestinationPath, cancellationToken);
            }
            else
            {
                await blob.DownloadToAsync(fullDestinationPath, cancellationToken);
            }

            var encoding = GetEncoding(options.Encoding, options.OtherEncoding);
            CheckAndFixFileEncoding(fullDestinationPath, input.TargetDirectory, fileExtension, encoding);

            return new Result { Success = true, FilePath = fullDestinationPath, Error = null };
        }
        catch (Exception ex)
        {
            return ErrorHandler.Handle(ex, options.ThrowErrorOnFailure, options.ErrorMessageOnFailure);
        }
    }

    private static void CheckAndFixFileEncoding(string fullPath, string directory, string fileExtension,
    Encoding targetEncoding)
    {
        var targetPreamble = targetEncoding.GetPreamble();
        bool preambleMatches = true;

        if (targetPreamble.Length > 0)
        {
            var headerBytes = new byte[targetPreamble.Length];
            using (var fs = new FileStream(fullPath, FileMode.Open, FileAccess.Read))
            {
                fs.Read(headerBytes, 0, targetPreamble.Length);
            }
            preambleMatches = headerBytes.SequenceEqual(targetPreamble);
        }

        Encoding detectedEncoding;
        using (var reader = new StreamReader(fullPath, detectEncodingFromByteOrderMarks: true))
        {
            reader.Read();
            detectedEncoding = reader.CurrentEncoding;
        }

        bool encodingMatches = detectedEncoding.BodyName == targetEncoding.BodyName;

        if (!encodingMatches || !preambleMatches)
        {
            var tempFilePath = Path.Combine(Path.GetTempPath(), $"encodingTemp_{Guid.NewGuid()}{fileExtension}");

            try
            {
                using (var sr = new StreamReader(fullPath, detectEncodingFromByteOrderMarks: true))
                using (var sw = new StreamWriter(tempFilePath, false, targetEncoding))
                {
                    sw.Write(sr.ReadToEnd());
                }

                File.Copy(tempFilePath, fullPath, overwrite: true);
            }
            finally
            {
                if (File.Exists(tempFilePath))
                    File.Delete(tempFilePath);
            }
        }
    }

    private static Encoding GetEncoding(FileEncoding encoding, string encodingString)
    {
        switch (encoding)
        {
            case FileEncoding.UTF8WithBOM:
                return new UTF8Encoding(true);
            case FileEncoding.UTF8:
                return new UTF8Encoding(false);
            case FileEncoding.ASCII:
                return new ASCIIEncoding();
            case FileEncoding.Default:
                return Encoding.Default;
            case FileEncoding.Windows1252:
                return CodePagesEncodingProvider.Instance.GetEncoding("windows-1252");
            case FileEncoding.Other:
                try
                {
                    var encodingFromString = CodePagesEncodingProvider.Instance.GetEncoding(encodingString);

                    if (encodingFromString == null)
                        throw new ArgumentException($"Encoding '{encodingString}' is not supported.");

                    return encodingFromString;
                }
                catch (ArgumentException ex)
                {
                    throw new ArgumentException($"Invalid encoding string '{encodingString}': {ex.Message}");
                }
            default:
                throw new ArgumentOutOfRangeException($"Unknown Encoding type: '{encoding}'.");
        }
    }
}
