<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.17.1" />
      <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\FrendsTasks\Frends.Common.Toolkit\Frends.Common.Toolkit\Frends.Common.Toolkit.csproj" />
    </ItemGroup>

</Project>
