using Frends.AzureBlobStorage.DeleteContainer.Definitions;
using System;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.DeleteContainer.Helpers;

namespace Frends.AzureBlobStorage.DeleteContainer;

/// <summary>
/// Azure Blob Storage Task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Deletes a container from Azure blob storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.DeleteContainer)
    /// </summary>
    /// <param name="input">Information about the container destination.</param>
    /// <param name="connection">Connection parameters</param>
    /// <param name="options">Options regarding the error handling.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, object Error { string Message, object AdditionalInfo } }</returns>
    public static async Task<Result> DeleteContainer([PropertyTab] Input input, [PropertyTab] Connection connection,
        [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        try
        {
            ValidationHandler.Run(input, connection);
            var container =
                ConnectionHandler.GetBlobContainerClient(connection, input.ContainerName, cancellationToken);

            var result = await container.DeleteIfExistsAsync(null, cancellationToken);

            return new Result(result, null);
        }
        catch (Exception e)
        {
            return ErrorHandler.Handle(e, options.ThrowErrorOnFailure, options.ErrorMessageOnFailure);
        }
    }
}
