using Frends.AzureBlobStorage.DeleteContainer.Definitions;
using System;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.Toolkit.Definitions;
using Frends.AzureBlobStorage.Toolkit.Handlers;
using Frends.Common.Toolkit.Handlers;

namespace Frends.AzureBlobStorage.DeleteContainer;

/// <summary>
/// Azure Blob Storage Task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Deletes a container from Azure blob storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.DeleteContainer)
    /// </summary>
    /// <param name="input">Information about the container destination.</param>
    /// <param name="connection">Connection parameters</param>
    /// <param name="options">Options regarding the error handling.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { string ContainerWasDeleted, string Message }</returns>
    public static async Task<Result> DeleteContainer([PropertyTab] Input input, [PropertyTab] Connection connection,
        [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        try
        {
            ValidationHandler.Run(input, connection);
            var container =
                ConnectionHandler.GetBlobContainerClient(connection, input.ContainerName, cancellationToken);

            if (!await container.ExistsAsync(cancellationToken) && !options.ThrowErrorIfContainerDoesNotExists)
                return new Result(false, "Container not found.");

            if (!await container.ExistsAsync(cancellationToken) && options.ThrowErrorIfContainerDoesNotExists)
                throw new Exception("DeleteContainer error: Container not found.");

            var result = await container.DeleteIfExistsAsync(null, cancellationToken);

            return new Result(result, "Container deleted successfully.");
        }
        catch (Exception e)
        {
            throw new Exception("DeleteContainer: Error occured while trying to delete blob container.", e);
        }
    }
}
