using Azure;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Frends.AzureBlobStorage.WriteBlob.Definitions;
using MimeMapping;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO.Compression;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.WriteBlob.Helpers;

namespace Frends.AzureBlobStorage.WriteBlob;

/// <summary>
/// Azure Blob Storage Task.
/// </summary>
public class AzureBlobStorage
{
    /// <summary>
    /// Frends Task to write content to Azure Blob Storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.WriteBlob)
    /// </summary>
    /// <param name="source">Source parameters.</param>
    /// <param name="connection">Destination parameters.</param>
    /// <param name="options">Optional parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, string Info, string Uri }</returns>
    public static async Task<Result> WriteBlob(
		[PropertyTab] Input source, 
		[PropertyTab] Connection connection,
        [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        CheckDestinationParameters(connection);

        try
        {
            BlobClient blobClient = ConnectionHandler.GetBlobClient(connection, cancellationToken);

            if (connection.CreateContainerIfItDoesNotExist)
            {
                var containerClient = ConnectionHandler.GetBlobContainerClient(connection, cancellationToken);
                await CreateContainerIfItDoesNotExist(containerClient, cancellationToken);
            }

            var info = await HandleWrite(blobClient, source, connection, cancellationToken);
            var jsonInfo = SerializeBlobContentInfo(info);

            return new Result(true, jsonInfo, blobClient.Uri.ToString());
        }
        catch (Exception)
        {
            if (options.ThrowErrorOnFailure)
                throw;

            return new Result(false, null, null);
        }
    }

    private static async Task<BlobContentInfo> HandleWrite(
		BlobClient blobClient, 
		Input input,
        Connection connection, CancellationToken cancellationToken)
    {
        var overwrite = connection.HandleExistingFile == HandleExistingFile.Overwrite;
        var encoding = GetEncoding(input.Encoding, input.FileEncodingString, input.EnableBOM) ??
                       throw new Exception("Encoding was invalid.");
        byte[] bytes = input.SourceType == SourceType.String
            ? encoding.GetBytes(input.ContentString)
            : input.ContentBytes;
        if (connection.Compress)
            bytes = Compress(bytes);
        var tags = connection.Tags != null
            ? connection.Tags.ToDictionary(tag => tag.Name, tag => tag.Value)
            : new Dictionary<string, string>();

        var uploadOptions = new BlobUploadOptions
        {
            Conditions = overwrite ? null : new BlobRequestConditions { IfNoneMatch = new ETag("*") },
            HttpHeaders =
                new BlobHttpHeaders
                {
                    ContentType =
                        MimeUtility.GetMimeMapping(connection.Compress ? "gz" : connection.BlobName),
                    ContentEncoding = encoding.WebName
                },
            Tags = tags.Count > 0 ? tags : null
        };

        return await blobClient.UploadAsync(BinaryData.FromBytes(bytes), uploadOptions, cancellationToken)
            .ConfigureAwait(false);
    }

    private static string SerializeBlobContentInfo(BlobContentInfo info)
    {
        var dto = new ContentInfo
        {
            ETag = info.ETag.ToString(),
            LastModified = info.LastModified,
            ContentHash = info.ContentHash != null ? Convert.ToBase64String(info.ContentHash) : null,
            VersionId = info.VersionId,
            EncryptionKeySha256 = info.EncryptionKeySha256,
            EncryptionScope = info.EncryptionScope,
            BlobSequenceNumber = info.BlobSequenceNumber
        };

        var infoJson = JsonSerializer.Serialize(dto, new JsonSerializerOptions { WriteIndented = true });

        return infoJson;
    }

    private static async Task CreateContainerIfItDoesNotExist(BlobContainerClient containerClient,
        CancellationToken cancellationToken)
    {
        try
        {
            await containerClient.CreateIfNotExistsAsync(PublicAccessType.None, null, cancellationToken);
        }
        catch (Exception ex)
        {
            throw new Exception(
                $"An error occurred while checking if container exists or while creating a new container.", ex);
        }
    }

    private static Encoding GetEncoding(FileEncoding encoding, string encodingString, bool enableBom)
    {
        return encoding switch
        {
            FileEncoding.UTF8 => enableBom ? new UTF8Encoding(true) : new UTF8Encoding(false),
            FileEncoding.ASCII => new ASCIIEncoding(),
            FileEncoding.Default => Encoding.Default,
            FileEncoding.WINDOWS1252 => CodePagesEncodingProvider.Instance.GetEncoding("windows-1252"),
            FileEncoding.Other => CodePagesEncodingProvider.Instance.GetEncoding(encodingString),
            _ => throw new ArgumentOutOfRangeException($"Unknown Encoding type: '{encoding}'."),
        };
    }

    private static void CheckDestinationParameters(Connection connection)
    {
        if (connection.AuthenticationMethod is AuthenticationMethod.OAuth2 &&
            (string.IsNullOrEmpty(connection.ApplicationId) || string.IsNullOrEmpty(connection.ClientSecret) ||
             string.IsNullOrEmpty(connection.TenantId) || string.IsNullOrEmpty(connection.Uri)))
            throw new Exception(
				"Connection.Uri, Connection.ClientSecret, Connection.ApplicationId, and Connection.TenantId parameters can't be empty when Connection.AuthenticationMethod = OAuth2.");
        if (connection.AuthenticationMethod is AuthenticationMethod.ConnectionString &&
            string.IsNullOrEmpty(connection.ConnectionString))
            throw new Exception(
                "Connection.ConnectionString parameter can't be empty when Connection.AuthenticationMethod = ConnectionString.");
        if (connection.AuthenticationMethod is AuthenticationMethod.SASToken &&
            (string.IsNullOrEmpty(connection.SasToken) || string.IsNullOrEmpty(connection.Uri)))
            throw new Exception(
                "Connection.SasToken and Connection.Uri parameters can't be empty when Connection.AuthenticationMethod = SASToken.");
        if (string.IsNullOrEmpty(connection.ContainerName))
            throw new Exception("Connection.ContainerName parameter can't be empty.");
        if (string.IsNullOrEmpty(connection.BlobName))
            throw new Exception("Connection.BlobName parameter can't be empty.");
        ValidateContainerName(connection.ContainerName);
    }

    private static void ValidateContainerName(string container)
    {
        if (container.Length < 3)
            throw new Exception("Container name is too short. Name needs to be between 3 and 63 characters.");
        if (container.Length > 63)
            throw new Exception("Container name is too long. Name needs to be between 3 and 63 characters.");
        if (!Regex.IsMatch(container, @"^[a-z0-9]+(-[a-z0-9]+)*$"))
            throw new Exception(
                "Container name includes invalid characters. See more information: https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names");
    }

    private static byte[] Compress(byte[] original)
    {
        using var msi = new MemoryStream(original);
        using var mso = new MemoryStream();

        using (var gs = new GZipStream(mso, CompressionMode.Compress))
        {
            CopyTo(msi, gs);
        }

        return mso.ToArray();
    }

    private static void CopyTo(Stream src, Stream dest)
    {
        byte[] bytes = new byte[4096];

        int cnt;

        while ((cnt = src.Read(bytes, 0, bytes.Length)) != 0)
        {
            dest.Write(bytes, 0, cnt);
        }
    }
}
