using System;
using System.ComponentModel;
using System.Threading;
using System.Text;
using Frends.AzureBlobStorage.ReadBlob.Definitions;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.ReadBlob.Helpers;

namespace Frends.AzureBlobStorage.ReadBlob;

/// <summary>
/// Azure Storage task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Frends Task for encoding and reading a single blob from Azure Storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.ReadBlob)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, string Content, Error Error }</returns>
    public static async Task<Result> ReadBlob([PropertyTab] Input input, [PropertyTab] Connection connection, [PropertyTab] Options options,
        CancellationToken cancellationToken)
    {
        try
        {
            ValidationHandler.Run(input, connection);
            var blob = ConnectionHandler.GetBlobClient(connection, input.ContainerName, input.BlobName, cancellationToken);
            var result = await blob.DownloadContentAsync(cancellationToken);

            return new Result
            {
                Success = true,
                Content = SetStringEncoding(result.Value.Content.ToString(), options.Encoding),
                Error = null,
            };
        }
        catch (Exception ex)
        {
            return ErrorHandler.Handle(ex, options.ThrowErrorOnFailure, options.ErrorMessageOnFailure);
        }
    }

    private static string SetStringEncoding(string text, Encode encoding)
    {
        var bytes = Encoding.UTF8.GetBytes(text);

        return encoding switch
        {
            Encode.UTF8 => Encoding.UTF8.GetString(bytes),
            Encode.UTF32 => Encoding.UTF32.GetString(bytes),
            Encode.Unicode => Encoding.Unicode.GetString(bytes),
            Encode.ASCII => Encoding.ASCII.GetString(bytes),
            _ => Encoding.UTF8.GetString(bytes),
        };
    }
}
