using System;
using System.ComponentModel;
using System.Threading;
using System.Text;
using Azure.Storage.Blobs;
using Azure;
using Frends.AzureBlobStorage.ReadBlob.Definitions;
using System.Threading.Tasks;
using Azure.Identity;
using Frends.AzureBlobStorage.ReadBlob.Helpers;

namespace Frends.AzureBlobStorage.ReadBlob;

/// <summary>
/// Azure Storage task.
/// </summary>
public class AzureBlobStorage
{
    /// <summary>
    /// Frends Task for encoding and reading a single blob from Azure Storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.ReadBlob)
    /// </summary>
    /// <param name="source">Source parameters.</param>
    /// <param name="options">Options parameters</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { string Content }</returns>
    public static async Task<Result> ReadBlob([PropertyTab] Source source, [PropertyTab] Options options,
        CancellationToken cancellationToken)
    {
        var blob = ConnectionHandler.GetBlobClient(source, cancellationToken);
        var result = await blob.DownloadContentAsync(cancellationToken);

        return new Result(SetStringEncoding(result.Value.Content.ToString(), options.Encoding));
    }

    private static string SetStringEncoding(string text, Encode encoding)
    {
        var bytes = Encoding.UTF8.GetBytes(text);

        return encoding switch
        {
            Encode.UTF8 => Encoding.UTF8.GetString(bytes),
            Encode.UTF32 => Encoding.UTF32.GetString(bytes),
            Encode.Unicode => Encoding.Unicode.GetString(bytes),
            Encode.ASCII => Encoding.ASCII.GetString(bytes),
            _ => Encoding.UTF8.GetString(bytes),
        };
    }
}
