using System;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using Frends.AzureBlobStorage.CreateContainer.Definitions;
using Azure.Storage.Blobs.Models;
using Frends.AzureBlobStorage.CreateContainer.Helpers;

namespace Frends.AzureBlobStorage.CreateContainer;

/// <summary>
/// Azure Blob Storage Task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Frends Task for creating a container to Azure Blob Storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.CreateContainer)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, string Uri, object Error { string Message, Exception AdditionalInfo } }</returns>
    public static async Task<Result> CreateContainer([PropertyTab] Input input, [PropertyTab] Connection connection,
        [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        try
        {
            var container = ConnectionHandler.GetBlobContainerClient(connection, input, cancellationToken);
            await container.CreateIfNotExistsAsync(PublicAccessType.None, null, null, cancellationToken);

            return new Result { Success = true, Uri = container.Uri.ToString(), };
        }
        catch (Exception e) when (e is not OperationCanceledException)
        {
            return ErrorHandler.Handle(e, options.ThrowErrorOnFailure, options.ErrorMessageOnFailure);
        }
    }
}
