using Azure.Storage.Blobs.Models;
using Frends.AzureBlobStorage.DeleteBlob.Definitions;
using System;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.DeleteBlob.Helpers;

namespace Frends.AzureBlobStorage.DeleteBlob;

/// <summary>
/// Azure Blob Storage task.
/// </summary>
public static class AzureBlobStorage
{
	/// <summary>
	/// Delete a single blob from Azure Blob Storage.
	/// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.DeleteBlob)
	/// </summary>
	/// <param name="input">Input parameters.</param>
	/// <param name="connection">Connection parameters.</param>
	/// <param name="options">Options parameters</param>
	/// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
	/// <returns>Object { bool Success, string Info }</returns>
	public static async Task<Result> DeleteBlob([PropertyTab] Input input, [PropertyTab] Connection connection, [PropertyTab] Options options,
        CancellationToken cancellationToken)
    {
		var blobClient = ConnectionHandler.GetBlobClient(input, connection, cancellationToken);

        try
        {
            if (!await blobClient.ExistsAsync(cancellationToken) && !options.ThrowErrorIfBlobDoesNotExists)
                return new Result(false, $"Blob {input.BlobName} doesn't exist in container {connection.ContainerName}.");

            if (!await blobClient.ExistsAsync(cancellationToken) && options.ThrowErrorIfBlobDoesNotExists)
                throw new Exception($"Blob {input.BlobName} doesn't exist in container {connection.ContainerName}.");

			var accessCondition = string.IsNullOrWhiteSpace(options.VerifyETagWhenDeleting)
                ? new BlobRequestConditions { IfMatch = new Azure.ETag(options.VerifyETagWhenDeleting) }
                : null;

            var result = await blobClient.DeleteIfExistsAsync(
				ConvertEnum<DeleteSnapshotsOption>(options.SnapshotDeleteOption),
				accessCondition,
                cancellationToken);

            return new Result(result, $"Blob {input.BlobName} deleted from container {connection.ContainerName}.");
        }
        catch (Exception e)
        {
            throw new Exception("DeleteBlobAsync: An error occured while trying to delete blob", e);
        }
    }

    private static TEnum ConvertEnum<TEnum>(Enum source)
    {
        return (TEnum)Enum.Parse(typeof(TEnum), source.ToString(), true);
    }
}
