using Azure.Storage.Blobs.Models;
using System;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureBlobStorage.DeleteBlob.Definitions;
using Frends.AzureBlobStorage.DeleteBlob.Helpers;

namespace Frends.AzureBlobStorage.DeleteBlob;

/// <summary>
/// Azure Blob Storage task.
/// </summary>
public static class AzureBlobStorage
{
    /// <summary>
    /// Delete a single blob from Azure Blob Storage.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureBlobStorage.DeleteBlob)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, DeleteBlobError Error }</returns>
    public static async Task<Result> DeleteBlob([PropertyTab] Input input, [PropertyTab] Connection connection,
        [PropertyTab] Options options,
        CancellationToken cancellationToken)
    {
        try
        {
            ValidationHandler.Run(input, connection);
            var blob = ConnectionHandler.GetBlobClient(connection, input.ContainerName, input.BlobName,
                cancellationToken);

            var accessCondition = !string.IsNullOrWhiteSpace(options.VerifyETagWhenDeleting)
                ? new BlobRequestConditions
                {
                    IfMatch = new Azure.ETag(options.VerifyETagWhenDeleting)
                }
                : null;

            var deleted = await blob.DeleteIfExistsAsync(
                ConvertEnum<DeleteSnapshotsOption>(options.SnapshotDeleteOption), accessCondition,
                cancellationToken);

            return new Result(deleted);
        }
        catch (Exception e)
        {
            return ErrorHandler.Handle(e, options.ThrowErrorOnFailure, options.ErrorMessageOnFailure);
        }
    }

    private static TEnum ConvertEnum<TEnum>(Enum source)
    {
        return (TEnum)Enum.Parse(typeof(TEnum), source.ToString(), true);
    }
}
