name: DeleteContainer_push

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.AzureBlobStorage.DeleteContainer/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.AzureBlobStorage.DeleteContainer
      env_var_name_1: HiQ_AzureBlobStorage_ConnString
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_AZUREBLOBSTORAGE_CONNSTRING }}
