name: DownloadBlob_release

on:
  workflow_dispatch:
    paths:
      - 'Frends.AzureBlobStorage.DownloadBlob/**'

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.AzureBlobStorage.DownloadBlob
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      