name: AzureBlobStorage Toolkit Release
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.AzureBlobStorage.Toolkit/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/toolkit_release.yml@main
    with:
      working-directory: 'Frends.AzureBlobStorage.Toolkit'
      project-directory: 'Frends.AzureBlobStorage.Toolkit'
    secrets: inherit
